name: Android CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
NeuralOS/
│
├── app/
├── cloud/
│
├── .github/
│   └── workflows/
│       └── neural_pipeline.yml  ✅
│
├── gradle/
├── build.gradle
├── settings.gradle
...

      - name: Give permission
        run: chmod +x gradlew

      - name: Build (force même si erreur)
        run: ./gradlew assembleDebug || true